-- Seed data: food item list extracted from the EC and ZC kitchen stocklists,
-- loaded per lodge (item lists are fully separate per location, same as
-- the beverage app). Each row also seeds opening stock for period 2026-07
-- using the most recent counted stock figure found in the source file for
-- that item.
--
-- Units: purchase_unit and recipe_unit are set to the same value with a
-- 1:1 conversion factor for every item — as agreed, the messy raw units in
-- the source file ("pkt", "PKt", "600gr", etc.) weren't relied on. Only
-- clearly unambiguous units (KG, L, ml, g and obvious variants) were
-- mapped automatically; everything else defaulted to 'ea'. Review and set
-- real purchase/recipe units and conversion factors per item as you go —
-- especially before using an item in a recipe, since the recipe cost
-- calculation depends on the conversion factor being correct.
--
-- Prices came from the source file's price column; where it was blank,
-- the item was seeded at R0 opening cost — check these in the Opening tab.
-- 61 items had no price in the source file.
--
-- Note: a few names repeat within the same lodge under different
-- categories (e.g. "Dates" as fresh produce vs. dried in the pantry,
-- "Beef stock" as a liquid stock vs. a stock cube in spices) — these are
-- genuinely different products, kept as separate rows, matched here by
-- (location, category, name) rather than name alone so they don't collide.

with new_items(location_id, name, category, purchase_unit, recipe_unit, conversion_factor, cost, stock) as (
  values

    ('EC', 'Prawns', 'Meats / Fish', 'kg', 'kg', 1, 176.54, 1.5),
    ('EC', 'Ostrich', 'Meats / Fish', 'kg', 'kg', 1, 225.0, 3.0),
    ('EC', 'Springbok Carpaccio', 'Meats / Fish', 'ea', 'ea', 1, 54.74, 10.0),
    ('EC', 'Smoked Salmon', 'Meats / Fish', 'ea', 'ea', 1, 50.31, 8.0),
    ('EC', 'Beef fillet', 'Meats / Fish', 'kg', 'kg', 1, 250.0, 2.5),
    ('EC', 'Chicken fillet', 'Meats / Fish', 'kg', 'kg', 1, 90.0, 4.0),
    ('EC', 'Chicken wings', 'Meats / Fish', 'kg', 'kg', 1, 89.0, 8.0),
    ('EC', 'Whole chicken', 'Meats / Fish', 'kg', 'kg', 1, 75.0, 3.0),
    ('EC', 'Lamb roast', 'Meats / Fish', 'kg', 'kg', 1, 157.0, 0.0),
    ('EC', 'Kingklip', 'Meats / Fish', 'ea', 'ea', 1, 893.88, 1.5),
    ('EC', 'Salmon', 'Meats / Fish', 'ea', 'ea', 1, 194.0, 7.0),
    ('EC', 'Hake fillet', 'Meats / Fish', 'ea', 'ea', 1, 734.77, 1.0),
    ('EC', 'Sole fish', 'Meats / Fish', 'ea', 'ea', 1, 739.0, 1.0),
    ('EC', 'Game', 'Meats / Fish', 'ea', 'ea', 1, 0, 18.0),
    ('EC', 'Pork bellly', 'Meats / Fish', 'kg', 'kg', 1, 128.0, 10.0),
    ('EC', 'Bacon', 'Meats / Fish', 'kg', 'kg', 1, 123.0, 4.0),
    ('EC', 'Biltong', 'Meats / Fish', 'kg', 'kg', 1, 0, 2.0),
    ('EC', 'Pork Chops', 'Meats / Fish', 'kg', 'kg', 1, 95.0, 10.0),
    ('EC', 'Lamb Shanks', 'Meats / Fish', 'ea', 'ea', 1, 177.0, 17.0),
    ('EC', 'Lamb Racks', 'Meats / Fish', 'ea', 'ea', 1, 267.0, 15.0),
    ('EC', 'Lamb Chops', 'Meats / Fish', 'kg', 'kg', 1, 230.0, 12.0),
    ('EC', 'Sausages', 'Meats / Fish', 'kg', 'kg', 1, 77.3, 5.0),
    ('EC', 'Ox tail', 'Meats / Fish', 'kg', 'kg', 1, 0, 105.0),
    ('EC', 'Pork Fillet', 'Meats / Fish', 'kg', 'kg', 1, 115.0, 2.0),
    ('EC', 'Turkey', 'Meats / Fish', 'ea', 'ea', 1, 0, 0.0),
    ('EC', 'Duck Breat', 'Meats / Fish', 'kg', 'kg', 1, 360.0, 7.0),
    ('EC', 'Beef Rump', 'Meats / Fish', 'kg', 'kg', 1, 176.0, 2.0),
    ('EC', 'Boere Wors', 'Meats / Fish', 'kg', 'kg', 1, 122.0, 4.0),
    ('EC', 'Mince meat', 'Meats / Fish', 'kg', 'kg', 1, 112.0, 2.0),
    ('EC', 'Beef Sirloin', 'Meats / Fish', 'g', 'g', 1, 0, 2.0),
    ('EC', 'Buffalo fillet', 'Meats / Fish', 'kg', 'kg', 1, 750.0, 1.5),
    ('EC', 'Apricot', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0),
    ('EC', 'Brown Bread', 'Fresh and Veg', 'ea', 'ea', 1, 16.99, 5.0),
    ('EC', 'White Bread', 'Fresh and Veg', 'ea', 'ea', 1, 16.99, 8.0),
    ('EC', 'Butter - Saltes', 'Fresh and Veg', 'ea', 'ea', 1, 64.55, 8.0),
    ('EC', 'Crushed Garlic', 'Fresh and Veg', 'ea', 'ea', 1, 58.99, 0.5),
    ('EC', 'Breakfast Cheeses', 'Fresh and Veg', 'kg', 'kg', 1, 197.72, 1.5),
    ('EC', 'Cheddar', 'Fresh and Veg', 'kg', 'kg', 1, 117.11, 1.0),
    ('EC', 'Eggs', 'Fresh and Veg', 'ea', 'ea', 1, 70.0, 6.0),
    ('EC', 'Feta Cheese', 'Fresh and Veg', 'kg', 'kg', 1, 138.23, 1.0),
    ('EC', 'Fresh Cream', 'Fresh and Veg', 'ea', 'ea', 1, 59.99, 1.0),
    ('EC', 'Mozarella', 'Fresh and Veg', 'g', 'g', 1, 122.0, 1.0),
    ('EC', 'Fruits', 'Fresh and Veg', 'ea', 'ea', 1, 0, 5.0),
    ('EC', 'Lettuce', 'Fresh and Veg', 'ea', 'ea', 1, 21.99, 3.0),
    ('EC', 'Long Life Milk', 'Fresh and Veg', 'ea', 'ea', 1, 15.83, 16.0),
    ('EC', 'Olives', 'Fresh and Veg', 'kg', 'kg', 1, 41.0, 1.0),
    ('EC', 'Onions (kg)', 'Fresh and Veg', 'kg', 'kg', 1, 29.99, 2.0),
    ('EC', 'Oranges', 'Fresh and Veg', 'kg', 'kg', 1, 21.36, 15.0),
    ('EC', 'Potatoes (kg)', 'Fresh and Veg', 'kg', 'kg', 1, 10.71, 3.0),
    ('EC', 'Tomato', 'Fresh and Veg', 'kg', 'kg', 1, 29.99, 3.0),
    ('EC', 'Vegetables (enough?)', 'Fresh and Veg', 'ea', 'ea', 1, 18.0, 20.0),
    ('EC', 'Versati Cream', 'Fresh and Veg', 'L', 'L', 1, 58.33, 8.0),
    ('EC', 'Strawberry yoghurt', 'Fresh and Veg', 'kg', 'kg', 1, 38.99, 1.0),
    ('EC', 'Tropical yoghurt', 'Fresh and Veg', 'kg', 'kg', 1, 38.99, 3.0),
    ('EC', 'Mango & peach yoghurt', 'Fresh and Veg', 'kg', 'kg', 1, 38.99, 4.0),
    ('EC', 'Yoghurt Plain', 'Fresh and Veg', 'kg', 'kg', 1, 41.99, 2.0),
    ('EC', 'White mushrooms', 'Fresh and Veg', 'ea', 'ea', 1, 28.99, 7.0),
    ('EC', 'Brown mushroom', 'Fresh and Veg', 'ea', 'ea', 1, 34.99, 2.0),
    ('EC', 'Dates', 'Fresh and Veg', 'ea', 'ea', 1, 44.99, 3.5),
    ('EC', 'Litches', 'Fresh and Veg', 'ea', 'ea', 1, 41.46, 0.0),
    ('EC', 'Hp sauce', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('EC', 'Chorizo', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('EC', 'Lamb shank', 'Fresh and Veg', 'ea', 'ea', 1, 177.0, 2.5),
    ('EC', 'Cous cous', 'Fresh and Veg', 'ea', 'ea', 1, 0, 1.0),
    ('EC', 'Quinoa', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('EC', 'hake', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('EC', 'Aluminum foil', 'Dry- and other stock', 'ea', 'ea', 1, 154.18, 4.0),
    ('EC', 'Apple cider vinegar', 'Dry- and other stock', 'ea', 'ea', 1, 27.99, 0.5),
    ('EC', 'Apples in tin', 'Dry- and other stock', 'ea', 'ea', 1, 24.8, 4.0),
    ('EC', 'Apricot jam', 'Dry- and other stock', 'ea', 'ea', 1, 37.67, 4.0),
    ('EC', 'Tin Tuna', 'Dry- and other stock', 'ea', 'ea', 1, 18.54, 6.0),
    ('EC', 'Baked beans', 'Dry- and other stock', 'ea', 'ea', 1, 16.19, 5.0),
    ('EC', 'Baking powder', 'Dry- and other stock', 'kg', 'kg', 1, 33.54, 5.0),
    ('EC', 'Balsamic vinegar', 'Dry- and other stock', 'L', 'L', 1, 38.19, 2.0),
    ('EC', 'Basmati rice', 'Dry- and other stock', 'kg', 'kg', 1, 59.99, 4.0),
    ('EC', 'Bay leaves', 'Dry- and other stock', 'ea', 'ea', 1, 0, 0.5),
    ('EC', 'BBQ sauce', 'Dry- and other stock', 'L', 'L', 1, 20.0, 4.0),
    ('EC', 'Beef stock', 'Dry- and other stock', 'ea', 'ea', 1, 25.99, 3.0),
    ('EC', 'Black beans', 'Dry- and other stock', 'ea', 'ea', 1, 19.38, 0.0),
    ('EC', 'Chips', 'Dry- and other stock', 'ea', 'ea', 1, 19.99, 4.0),
    ('EC', 'Chocolate brown', 'Dry- and other stock', 'kg', 'kg', 1, 101.23, 4.0),
    ('EC', 'Chocolate sauce', 'Dry- and other stock', 'L', 'L', 1, 102.5, 4.0),
    ('EC', 'Chocolate white', 'Dry- and other stock', 'kg', 'kg', 1, 101.23, 3.0),
    ('EC', 'Cling wrap', 'Dry- and other stock', 'ea', 'ea', 1, 344.69, 4.0),
    ('EC', 'Cocao powder', 'Dry- and other stock', 'kg', 'kg', 1, 129.01, 5.0),
    ('EC', 'Cocoa Pops', 'Dry- and other stock', 'kg', 'kg', 1, 124.0, 1.0),
    ('EC', 'Coconut cream', 'Dry- and other stock', 'ea', 'ea', 1, 21.62, 3.0),
    ('EC', 'Coconut milk', 'Dry- and other stock', 'ea', 'ea', 1, 21.73, 2.0),
    ('EC', 'Condensed Milk', 'Dry- and other stock', 'ea', 'ea', 1, 29.38, 10.0),
    ('EC', 'Cooking spray', 'Dry- and other stock', 'ea', 'ea', 1, 39.02, 13.0),
    ('EC', 'Corn Flakes', 'Dry- and other stock', 'kg', 'kg', 1, 68.33, 1.0),
    ('EC', 'Corn Starch', 'Dry- and other stock', 'ea', 'ea', 1, 30.37, 1.0),
    ('EC', 'Croissants', 'Dry- and other stock', 'ea', 'ea', 1, 595.59, 2.5),
    ('EC', 'Custard powder', 'Dry- and other stock', 'kg', 'kg', 1, 35.16, 5.0),
    ('EC', 'Dates', 'Dry- and other stock', 'kg', 'kg', 1, 38.67, 2.0),
    ('EC', 'Frozen mix berries', 'Dry- and other stock', 'kg', 'kg', 1, 68.0, 3.5),
    ('EC', 'Frozen peas', 'Dry- and other stock', 'kg', 'kg', 1, 34.25, 1.0),
    ('EC', 'Fruit Chutney', 'Dry- and other stock', 'ea', 'ea', 1, 40.99, 3.0),
    ('EC', 'Gelatine', 'Dry- and other stock', 'kg', 'kg', 1, 215.8, 2.0),
    ('EC', 'Golden Syrup', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 6.0),
    ('EC', 'Granadilla in tin', 'Dry- and other stock', 'ea', 'ea', 1, 15.48, 0.0),
    ('EC', 'Honey', 'Dry- and other stock', 'ea', 'ea', 1, 82.99, 5.0),
    ('EC', 'Hot English mustard', 'Dry- and other stock', 'kg', 'kg', 1, 191.68, 1.0),
    ('EC', 'Ice cream', 'Dry- and other stock', 'L', 'L', 1, 166.99, 1.0),
    ('EC', 'Lasagna sheets', 'Dry- and other stock', 'ea', 'ea', 1, 73.99, 2.0),
    ('EC', 'Lemon and herb sauce', 'Dry- and other stock', 'ea', 'ea', 1, 35.99, 0.0),
    ('EC', 'Lemon juice', 'Dry- and other stock', 'ml', 'ml', 1, 21.99, 2.0),
    ('EC', 'Gluten free muesli', 'Dry- and other stock', 'ea', 'ea', 1, 0, 2.5),
    ('EC', 'Muesli', 'Dry- and other stock', 'ea', 'ea', 1, 69.99, 2.0),
    ('EC', 'Fusilli', 'Dry- and other stock', 'ea', 'ea', 1, 0, 2.0),
    ('EC', 'Macaroni', 'Dry- and other stock', 'kg', 'kg', 1, 33.99, 4.0),
    ('EC', 'Maple Syrup', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 4.0),
    ('EC', 'Mayonaise', 'Dry- and other stock', 'kg', 'kg', 1, 38.08, 3.0),
    ('EC', 'Oil - Olive', 'Dry- and other stock', 'L', 'L', 1, 65.01, 7.0),
    ('EC', 'Oil - Sunflower', 'Dry- and other stock', 'L', 'L', 1, 45.99, 3.0),
    ('EC', 'Parmasan cheese', 'Dry- and other stock', 'kg', 'kg', 1, 221.04, 0.5),
    ('EC', 'Peach halves', 'Dry- and other stock', 'ea', 'ea', 1, 21.4, 4.0),
    ('EC', 'Peanut butter', 'Dry- and other stock', 'ea', 'ea', 1, 75.55, 0.5),
    ('EC', 'Peanuts/raisins', 'Dry- and other stock', 'ea', 'ea', 1, 83.39, 2.0),
    ('EC', 'Pecan nuts', 'Dry- and other stock', 'kg', 'kg', 1, 317.89, 1.0),
    ('EC', 'Peppadew', 'Dry- and other stock', 'ea', 'ea', 1, 32.15, 0.0),
    ('EC', 'Phyllo pastry', 'Dry- and other stock', 'kg', 'kg', 1, 49.4, 0.0),
    ('EC', 'Pineapple in tin', 'Dry- and other stock', 'ea', 'ea', 1, 33.05, 6.0),
    ('EC', 'Puff pastry', 'Dry- and other stock', 'ea', 'ea', 1, 466.9, 2.0),
    ('EC', 'Raisins', 'Dry- and other stock', 'kg', 'kg', 1, 47.07, 2.0),
    ('EC', 'Rice vermiseli', 'Dry- and other stock', 'ea', 'ea', 1, 54.99, 2.0),
    ('EC', 'Risotto rice', 'Dry- and other stock', 'kg', 'kg', 1, 70.86, 1.0),
    ('EC', 'Salami', 'Dry- and other stock', 'ea', 'ea', 1, 56.99, 5.0),
    ('EC', 'Salted crackers', 'Dry- and other stock', 'ea', 'ea', 1, 34.99, 4.0),
    ('EC', 'Sandwich bags', 'Dry- and other stock', 'ea', 'ea', 1, 43.99, 3.0),
    ('EC', 'Self-raising Flower', 'Dry- and other stock', 'kg', 'kg', 1, 27.0, 10.0),
    ('EC', 'Sesame seeds', 'Dry- and other stock', 'kg', 'kg', 1, 84.08, 0.0),
    ('EC', 'Soy sauce', 'Dry- and other stock', 'ea', 'ea', 1, 98.28, 1.5),
    ('EC', 'Strawberry jam', 'Dry- and other stock', 'ea', 'ea', 1, 65.09, 4.0),
    ('EC', 'Sugar - Brown', 'Dry- and other stock', 'kg', 'kg', 1, 20.73, 4.0),
    ('EC', 'Sugar - Castor', 'Dry- and other stock', 'kg', 'kg', 1, 23.4, 3.0),
    ('EC', 'Sugar - Icing', 'Dry- and other stock', 'kg', 'kg', 1, 27.97, 5.0),
    ('EC', 'Sugar- White', 'Dry- and other stock', 'kg', 'kg', 1, 18.78, 5.0),
    ('EC', 'Sundried tomato', 'Dry- and other stock', 'ea', 'ea', 1, 35.99, 3.0),
    ('EC', 'Sunflower seeds', 'Dry- and other stock', 'ea', 'ea', 1, 59.99, 0.0),
    ('EC', 'Sweet Chili', 'Dry- and other stock', 'ea', 'ea', 1, 49.5, 6.0),
    ('EC', 'Tabasco', 'Dry- and other stock', 'ml', 'ml', 1, 51.99, 2.0),
    ('EC', 'Tennis biscuit', 'Dry- and other stock', 'ea', 'ea', 1, 23.99, 12.0),
    ('EC', 'Terriyaki sauce', 'Dry- and other stock', 'ea', 'ea', 1, 83.99, 0.0),
    ('EC', 'Tinned tomatoes', 'Dry- and other stock', 'ea', 'ea', 1, 14.03, 8.0),
    ('EC', 'Tomato paste', 'Dry- and other stock', 'ea', 'ea', 1, 11.01, 12.0),
    ('EC', 'Tomato sauce', 'Dry- and other stock', 'ml', 'ml', 1, 30.65, 2.0),
    ('EC', 'Tortilla wraps', 'Dry- and other stock', 'ea', 'ea', 1, 37.99, 12.0),
    ('EC', 'Tuna', 'Dry- and other stock', 'ea', 'ea', 1, 25.74, 9.0),
    ('EC', 'Vanilla Essence', 'Dry- and other stock', 'L', 'L', 1, 51.67, 4.0),
    ('EC', 'White vinegar', 'Dry- and other stock', 'L', 'L', 1, 10.05, 4.0),
    ('EC', 'Whole grain mustard', 'Dry- and other stock', 'ea', 'ea', 1, 36.84, 1.0),
    ('EC', 'Whole kennel corn', 'Dry- and other stock', 'ea', 'ea', 1, 24.99, 12.0),
    ('EC', 'Wall nuts', 'Dry- and other stock', 'kg', 'kg', 1, 175.53, 1.0),
    ('EC', 'Worchester sauce', 'Dry- and other stock', 'L', 'L', 1, 14.15, 3.0),
    ('EC', 'Yeast', 'Dry- and other stock', 'ea', 'ea', 1, 213.69, 13.0),
    ('EC', 'Caramel Treat', 'Dry- and other stock', 'ea', 'ea', 1, 30.55, 6.0),
    ('EC', 'Polenta', 'Dry- and other stock', 'ea', 'ea', 1, 31.99, 2.0),
    ('EC', 'Sweet Corn', 'Dry- and other stock', 'ea', 'ea', 1, 27.99, 2.0),
    ('EC', 'Brown Rice', 'Dry- and other stock', 'kg', 'kg', 1, 25.99, 1.5),
    ('EC', 'Golden syruo small', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 6.0),
    ('EC', 'Golden syrup big', 'Dry- and other stock', 'ea', 'ea', 1, 63.99, 1.0),
    ('EC', 'Maple Syrup smal', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 3.0),
    ('EC', 'Maple syrup big', 'Dry- and other stock', 'ea', 'ea', 1, 63.99, 0.0),
    ('EC', 'Honey small', 'Dry- and other stock', 'ea', 'ea', 1, 63.99, 4.0),
    ('EC', 'Honey big', 'Dry- and other stock', 'ea', 'ea', 1, 99.0, 0.0),
    ('EC', 'OrgininalChutney', 'Dry- and other stock', 'ea', 'ea', 1, 40.99, 3.0),
    ('EC', 'Spaghetti', 'Dry- and other stock', 'ea', 'ea', 1, 19.99, 4.0),
    ('EC', 'Chick peas', 'Dry- and other stock', 'ea', 'ea', 1, 26.99, 2.0),
    ('EC', 'Red cherries', 'Dry- and other stock', 'ea', 'ea', 1, 98.99, 0.0),
    ('EC', 'Green tabasco', 'Dry- and other stock', 'ea', 'ea', 1, 51.99, 8.0),
    ('EC', 'Red tabasco', 'Dry- and other stock', 'ea', 'ea', 1, 109.99, 6.0),
    ('EC', 'Cake flour', 'Dry- and other stock', 'kg', 'kg', 1, 17.99, 4.0),
    ('EC', 'White wheat flour', 'Dry- and other stock', 'kg', 'kg', 1, 20.39, 0.0),
    ('EC', 'Bread crumps', 'Dry- and other stock', 'ea', 'ea', 1, 29.99, 3.0),
    ('EC', 'Mint sauce', 'Dry- and other stock', 'ea', 'ea', 1, 44.99, 1.0),
    ('EC', 'Sweet & Sour', 'Dry- and other stock', 'ea', 'ea', 1, 77.99, 0.0),
    ('EC', 'Pie Apple slices', 'Dry- and other stock', 'ea', 'ea', 1, 34.99, 4.0),
    ('EC', 'Hot chocolate', 'Dry- and other stock', 'kg', 'kg', 1, 139.99, 2.5),
    ('EC', 'Tickle Sugar', 'Dry- and other stock', 'kg', 'kg', 1, 0, 1.0),
    ('EC', 'Cumin', 'Spices', 'ea', 'ea', 1, 42.99, 0.0),
    ('EC', 'Curry', 'Spices', 'ea', 'ea', 1, 70.96, 2.0),
    ('EC', 'Lemon and herb', 'Spices', 'ea', 'ea', 1, 60.36, 1.0),
    ('EC', 'Aromat', 'Spices', 'ea', 'ea', 1, 131.42, 2.0),
    ('EC', 'Mixed herbs', 'Spices', 'ea', 'ea', 1, 56.24, 1.0),
    ('EC', 'Vegetable seasoning', 'Spices', 'ea', 'ea', 1, 138.5, 1.0),
    ('EC', 'Vegetable stock', 'Spices', 'ea', 'ea', 1, 0, 1.0),
    ('EC', 'Turmeric', 'Spices', 'ea', 'ea', 1, 154.97, 1.0),
    ('EC', 'Salt', 'Spices', 'kg', 'kg', 1, 5.18, 3.0),
    ('EC', 'Oregano', 'Spices', 'ea', 'ea', 1, 45.37, 0.5),
    ('EC', 'Paprika spice', 'Spices', 'ea', 'ea', 1, 78.64, 0.5),
    ('EC', 'Chicken spice', 'Spices', 'ea', 'ea', 1, 43.83, 0.5),
    ('EC', 'Chicken stock', 'Spices', 'ea', 'ea', 1, 0, 2.0),
    ('EC', 'Cajun spice', 'Spices', 'ea', 'ea', 1, 89.43, 1.0),
    ('EC', 'Chip Seasoning', 'Spices', 'ea', 'ea', 1, 46.0, 0.5),
    ('EC', 'Black pepper', 'Spices', 'ea', 'ea', 1, 410.17, 1.0),
    ('EC', 'Rosemary', 'Spices', 'ea', 'ea', 1, 0, 0.0),
    ('EC', 'Fish Spice', 'Spices', 'ea', 'ea', 1, 50.24, 2.0),
    ('EC', 'Cinnamom ground', 'Spices', 'ea', 'ea', 1, 64.84, 0.5),
    ('EC', 'Ground ginger', 'Spices', 'ea', 'ea', 1, 89.37, 1.0),
    ('EC', 'Cayenne pepper', 'Spices', 'ea', 'ea', 1, 75.13, 0.0),
    ('EC', 'Steak & Chop', 'Spices', 'ea', 'ea', 1, 57.79, 0.0),
    ('EC', 'White Pepper', 'Spices', 'ea', 'ea', 1, 140.01, 1.0),
    ('EC', 'Beef stock', 'Spices', 'ea', 'ea', 1, 0, 0.5),
    ('EC', 'Nutmeg ground', 'Spices', 'ea', 'ea', 1, 255.78, 1.0),
    ('EC', 'Meat tenderiser', 'Spices', 'ea', 'ea', 1, 58.35, 2.0),
    ('EC', 'Thyme', 'Spices', 'ea', 'ea', 1, 0, 1.0),
    ('EC', 'Portugese chicken', 'Spices', 'ea', 'ea', 1, 53.28, 0.0),
    ('EC', 'BBQ spice', 'Spices', 'ea', 'ea', 1, 62.8, 1.0),
    ('EC', 'Mixed spice', 'Spices', 'ea', 'ea', 1, 87.64, 1.0),
    ('EC', 'Pepper', 'Spices', 'ea', 'ea', 1, 0, 0.5),
    ('EC', 'Coarse pepper', 'Spices', 'ea', 'ea', 1, 0, 0.5),
    ('EC', 'Lamb riblets', 'Spices', 'kg', 'kg', 1, 0, 0.5),
    ('EC', 'Gammom', 'Spices', 'kg', 'kg', 1, 0, 0.0),
    ('EC', 'Squid Sticks', 'Spices', 'ea', 'ea', 1, 0, 2.0),
    ('EC', 'Beef short ribs', 'Spices', 'kg', 'kg', 1, 0, 0.0),
    ('EC', 'Italian Herbs', 'Spices', 'kg', 'kg', 1, 0, 0.0),
    ('EC', 'Six gun', 'Spices', 'kg', 'kg', 1, 0, 1.0),
    ('ZC', 'Prawns', 'Meats / Fish', 'kg', 'kg', 1, 176.54, 4.0),
    ('ZC', 'Ostrich', 'Meats / Fish', 'kg', 'kg', 1, 225.0, 0.0),
    ('ZC', 'Springbok Carpaccio', 'Meats / Fish', 'ea', 'ea', 1, 54.74, 0.0),
    ('ZC', 'Smoked Salmon', 'Meats / Fish', 'ea', 'ea', 1, 50.31, 5.0),
    ('ZC', 'Beef fillet', 'Meats / Fish', 'kg', 'kg', 1, 250.0, 2.0),
    ('ZC', 'Chicken fillet', 'Meats / Fish', 'kg', 'kg', 1, 90.0, 4.0),
    ('ZC', 'Chicken wings', 'Meats / Fish', 'kg', 'kg', 1, 89.0, 8.0),
    ('ZC', 'Whole chicken', 'Meats / Fish', 'kg', 'kg', 1, 75.0, 2.0),
    ('ZC', 'Lamb roast', 'Meats / Fish', 'kg', 'kg', 1, 157.0, 0.0),
    ('ZC', 'Kingklip', 'Meats / Fish', 'ea', 'ea', 1, 893.88, 1.0),
    ('ZC', 'Sole fish', 'Meats / Fish', 'ea', 'ea', 1, 803.55, 0.8),
    ('ZC', 'Game', 'Meats / Fish', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Pork bellly', 'Meats / Fish', 'kg', 'kg', 1, 128.0, 6.0),
    ('ZC', 'Bacon', 'Meats / Fish', 'kg', 'kg', 1, 123.0, 4.0),
    ('ZC', 'Biltong', 'Meats / Fish', 'ea', 'ea', 1, 0, 3.0),
    ('ZC', 'Pork Chops', 'Meats / Fish', 'kg', 'kg', 1, 95.0, 4.0),
    ('ZC', 'Lamb Chops', 'Meats / Fish', 'kg', 'kg', 1, 230.0, 2.0),
    ('ZC', 'Sausages', 'Meats / Fish', 'ea', 'ea', 1, 77.3, 4.0),
    ('ZC', 'Ox tail', 'Meats / Fish', 'ea', 'ea', 1, 0, 2.0),
    ('ZC', 'Pork Fillet', 'Meats / Fish', 'kg', 'kg', 1, 115.0, 4.0),
    ('ZC', 'Turkey', 'Meats / Fish', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Duck Breat', 'Meats / Fish', 'kg', 'kg', 1, 360.0, 2.0),
    ('ZC', 'Beef Rump', 'Meats / Fish', 'kg', 'kg', 1, 176.0, 0.5),
    ('ZC', 'Boere Wors', 'Meats / Fish', 'kg', 'kg', 1, 122.0, 0.0),
    ('ZC', 'Mince meat', 'Meats / Fish', 'kg', 'kg', 1, 0, 2.0),
    ('ZC', 'Lamb racks', 'Meats / Fish', 'kg', 'kg', 1, 0, 0.0),
    ('ZC', 'Fish fingers', 'Meats / Fish', 'kg', 'kg', 1, 0, 0.0),
    ('ZC', 'Hake fillet', 'Meats / Fish', 'kg', 'kg', 1, 0, 0.0),
    ('ZC', 'Salmon', 'Meats / Fish', 'kg', 'kg', 1, 0, 0.0),
    ('ZC', 'Buffalo fillet', 'Meats / Fish', 'kg', 'kg', 1, 750.0, 0.0),
    ('ZC', 'Mixed Nuts', 'Meats / Fish', 'kg', 'kg', 1, 136.19, 0.0),
    ('ZC', 'Apricot', 'Fresh and Veg', 'ea', 'ea', 1, 0, 3.0),
    ('ZC', 'Brown Bread', 'Fresh and Veg', 'ea', 'ea', 1, 16.99, 4.0),
    ('ZC', 'White Bread', 'Fresh and Veg', 'ea', 'ea', 1, 16.99, 3.0),
    ('ZC', 'Butter - Saltes', 'Fresh and Veg', 'ea', 'ea', 1, 64.55, 10.0),
    ('ZC', 'Crushed Garlic', 'Fresh and Veg', 'ea', 'ea', 1, 58.99, 1.0),
    ('ZC', 'Breakfast Cheeses', 'Fresh and Veg', 'kg', 'kg', 1, 197.72, 2.0),
    ('ZC', 'Cheddar', 'Fresh and Veg', 'kg', 'kg', 1, 117.11, 1.5),
    ('ZC', 'Eggs', 'Fresh and Veg', 'ea', 'ea', 1, 70.0, 5.0),
    ('ZC', 'Feta Cheese', 'Fresh and Veg', 'kg', 'kg', 1, 138.23, 1.0),
    ('ZC', 'Fresh Cream', 'Fresh and Veg', 'ea', 'ea', 1, 59.99, 0.0),
    ('ZC', 'Mozarella', 'Fresh and Veg', 'g', 'g', 1, 122.0, 1.0),
    ('ZC', 'Fruits', 'Fresh and Veg', 'ea', 'ea', 1, 0, 2.0),
    ('ZC', 'Lettuce', 'Fresh and Veg', 'ea', 'ea', 1, 21.99, 5.0),
    ('ZC', 'Long Life Milk', 'Fresh and Veg', 'ea', 'ea', 1, 15.83, 6.0),
    ('ZC', 'Olives', 'Fresh and Veg', 'kg', 'kg', 1, 41.0, 7.0),
    ('ZC', 'Onions (kg)', 'Fresh and Veg', 'kg', 'kg', 1, 29.99, 2.0),
    ('ZC', 'Oranges', 'Fresh and Veg', 'kg', 'kg', 1, 21.36, 11.0),
    ('ZC', 'Potatoes (kg)', 'Fresh and Veg', 'kg', 'kg', 1, 10.71, 9.0),
    ('ZC', 'Tomato', 'Fresh and Veg', 'kg', 'kg', 1, 29.99, 2.0),
    ('ZC', 'Vegetables (enough?)', 'Fresh and Veg', 'ea', 'ea', 1, 18.0, 30.0),
    ('ZC', 'Versati Cream', 'Fresh and Veg', 'ea', 'ea', 1, 58.33, 3.0),
    ('ZC', 'Yoghurt Flavoured', 'Fresh and Veg', 'kg', 'kg', 1, 38.99, 5.0),
    ('ZC', 'Yoghurt Plain', 'Fresh and Veg', 'kg', 'kg', 1, 41.99, 4.0),
    ('ZC', 'White mushrooms', 'Fresh and Veg', 'ea', 'ea', 1, 28.99, 2.0),
    ('ZC', 'Brown mushroom', 'Fresh and Veg', 'ea', 'ea', 1, 34.99, 3.0),
    ('ZC', 'Dates', 'Fresh and Veg', 'ea', 'ea', 1, 44.99, 3.0),
    ('ZC', 'Litches', 'Fresh and Veg', 'ea', 'ea', 1, 41.46, 0.0),
    ('ZC', 'Strawberry yoghurt', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Tropical yoghurt', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Mango and peach yoghurt', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Plain yoghurt', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'English muffins', 'Fresh and Veg', 'ea', 'ea', 1, 0, 9.0),
    ('ZC', 'Pita bread', 'Fresh and Veg', 'ea', 'ea', 1, 0, 3.0),
    ('ZC', 'Ciabatta', 'Fresh and Veg', 'ea', 'ea', 1, 0, 3.0),
    ('ZC', 'Hp sauce', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Cous cous', 'Fresh and Veg', 'ea', 'ea', 1, 0, 1.5),
    ('ZC', 'Hake', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Quinoa', 'Fresh and Veg', 'ea', 'ea', 1, 0, 2.0),
    ('ZC', 'Lentils', 'Fresh and Veg', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Aluminum foil', 'Dry- and other stock', 'ea', 'ea', 1, 154.18, 3.0),
    ('ZC', 'Apple cider vinegar', 'Dry- and other stock', 'ea', 'ea', 1, 27.99, 3.0),
    ('ZC', 'Apples in tin', 'Dry- and other stock', 'ea', 'ea', 1, 24.8, 3.0),
    ('ZC', 'Apricot jam', 'Dry- and other stock', 'ea', 'ea', 1, 37.67, 2.0),
    ('ZC', 'Baked beans', 'Dry- and other stock', 'ea', 'ea', 1, 16.19, 2.0),
    ('ZC', 'Baking powder', 'Dry- and other stock', 'kg', 'kg', 1, 33.54, 4.0),
    ('ZC', 'Balsamic vinegar', 'Dry- and other stock', 'L', 'L', 1, 38.19, 3.0),
    ('ZC', 'Basmati rice', 'Dry- and other stock', 'kg', 'kg', 1, 59.99, 4.0),
    ('ZC', 'Bay leaves', 'Dry- and other stock', 'ea', 'ea', 1, 0, 1.0),
    ('ZC', 'BBQ sauce', 'Dry- and other stock', 'L', 'L', 1, 20.0, 0.5),
    ('ZC', 'Beef stock', 'Dry- and other stock', 'ea', 'ea', 1, 25.99, 7.0),
    ('ZC', 'Black beans', 'Dry- and other stock', 'ea', 'ea', 1, 19.38, 5.0),
    ('ZC', 'Cereals', 'Dry- and other stock', 'kg', 'kg', 1, 77.4, 1.0),
    ('ZC', 'Chips', 'Dry- and other stock', 'ea', 'ea', 1, 19.99, 7.0),
    ('ZC', 'Chocolate brown', 'Dry- and other stock', 'kg', 'kg', 1, 101.23, 1.0),
    ('ZC', 'Chocolate sauce', 'Dry- and other stock', 'L', 'L', 1, 102.5, 2.0),
    ('ZC', 'Chocolate white', 'Dry- and other stock', 'kg', 'kg', 1, 101.23, 1.0),
    ('ZC', 'Cling foil', 'Dry- and other stock', 'ea', 'ea', 1, 344.69, 1.5),
    ('ZC', 'Cocao powder', 'Dry- and other stock', 'kg', 'kg', 1, 129.01, 2.0),
    ('ZC', 'Cocoa Pops', 'Dry- and other stock', 'kg', 'kg', 1, 124.0, 1.0),
    ('ZC', 'Coconut cream', 'Dry- and other stock', 'ea', 'ea', 1, 21.62, 5.0),
    ('ZC', 'Coconut milk', 'Dry- and other stock', 'ea', 'ea', 1, 21.73, 7.0),
    ('ZC', 'Condensed Milk', 'Dry- and other stock', 'ea', 'ea', 1, 29.38, 9.0),
    ('ZC', 'Cooking spray', 'Dry- and other stock', 'ea', 'ea', 1, 39.02, 15.0),
    ('ZC', 'Corn Flakes', 'Dry- and other stock', 'kg', 'kg', 1, 68.33, 1.0),
    ('ZC', 'Corn Starch', 'Dry- and other stock', 'ea', 'ea', 1, 30.37, 3.0),
    ('ZC', 'Croissants', 'Dry- and other stock', 'ea', 'ea', 1, 595.59, 3.0),
    ('ZC', 'Custard powder', 'Dry- and other stock', 'kg', 'kg', 1, 35.16, 4.0),
    ('ZC', 'Dates', 'Dry- and other stock', 'kg', 'kg', 1, 38.67, 3.0),
    ('ZC', 'Frozen mix berries', 'Dry- and other stock', 'kg', 'kg', 1, 68.0, 4.0),
    ('ZC', 'Frozen peas', 'Dry- and other stock', 'kg', 'kg', 1, 34.25, 5.0),
    ('ZC', 'Fruit Chutney', 'Dry- and other stock', 'ea', 'ea', 1, 40.99, 10.0),
    ('ZC', 'Gelatine', 'Dry- and other stock', 'kg', 'kg', 1, 215.8, 0.0),
    ('ZC', 'Golden Syrup', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 4.0),
    ('ZC', 'Granadilla in tin', 'Dry- and other stock', 'ea', 'ea', 1, 15.48, 4.0),
    ('ZC', 'Honey', 'Dry- and other stock', 'ea', 'ea', 1, 82.99, 8.0),
    ('ZC', 'Hot English mustard', 'Dry- and other stock', 'kg', 'kg', 1, 191.68, 3.0),
    ('ZC', 'Ice cream', 'Dry- and other stock', 'L', 'L', 1, 166.99, 0.5),
    ('ZC', 'Lasagna sheets', 'Dry- and other stock', 'ea', 'ea', 1, 73.99, 4.0),
    ('ZC', 'Lemon and herb sauce', 'Dry- and other stock', 'ea', 'ea', 1, 35.99, 2.0),
    ('ZC', 'Lemon juice', 'Dry- and other stock', 'ml', 'ml', 1, 21.99, 4.0),
    ('ZC', 'Muesli', 'Dry- and other stock', 'ea', 'ea', 1, 69.99, 6.0),
    ('ZC', 'Macaroni', 'Dry- and other stock', 'kg', 'kg', 1, 33.99, 5.0),
    ('ZC', 'Magalies juice', 'Dry- and other stock', 'L', 'L', 1, 58.99, 0.0),
    ('ZC', 'Maple Syrup', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 2.0),
    ('ZC', 'Mayonaise', 'Dry- and other stock', 'ea', 'ea', 1, 38.08, 0.0),
    ('ZC', 'Oil - Olive', 'Dry- and other stock', 'L', 'L', 1, 65.01, 1.0),
    ('ZC', 'Oil - Sunflower', 'Dry- and other stock', 'L', 'L', 1, 45.99, 2.0),
    ('ZC', 'Parmasan cheese', 'Dry- and other stock', 'kg', 'kg', 1, 221.04, 0.5),
    ('ZC', 'Peach halves', 'Dry- and other stock', 'ea', 'ea', 1, 21.4, 9.0),
    ('ZC', 'Peanut butter', 'Dry- and other stock', 'ea', 'ea', 1, 75.55, 1.0),
    ('ZC', 'Peanuts/raisins', 'Dry- and other stock', 'ea', 'ea', 1, 83.39, 2.0),
    ('ZC', 'Pecan nuts', 'Dry- and other stock', 'kg', 'kg', 1, 317.89, 1.5),
    ('ZC', 'Peppadew', 'Dry- and other stock', 'ea', 'ea', 1, 32.15, 0.0),
    ('ZC', 'Phyllo pastry', 'Dry- and other stock', 'kg', 'kg', 1, 49.4, 1.0),
    ('ZC', 'Pineapple in tin', 'Dry- and other stock', 'ea', 'ea', 1, 33.05, 3.0),
    ('ZC', 'Puff pastry', 'Dry- and other stock', 'ea', 'ea', 1, 466.9, 3.0),
    ('ZC', 'Raisins', 'Dry- and other stock', 'kg', 'kg', 1, 47.07, 3.0),
    ('ZC', 'Rice vermiseli', 'Dry- and other stock', 'ea', 'ea', 1, 54.99, 4.0),
    ('ZC', 'Risotto rice', 'Dry- and other stock', 'kg', 'kg', 1, 70.86, 6.0),
    ('ZC', 'Salami', 'Dry- and other stock', 'ea', 'ea', 1, 56.99, 2.0),
    ('ZC', 'Salted crackers', 'Dry- and other stock', 'ea', 'ea', 1, 34.99, 0.0),
    ('ZC', 'Sandwich bags', 'Dry- and other stock', 'ea', 'ea', 1, 43.99, 8.0),
    ('ZC', 'Self-raising Flower', 'Dry- and other stock', 'kg', 'kg', 1, 27.0, 15.0),
    ('ZC', 'Sesame seeds', 'Dry- and other stock', 'kg', 'kg', 1, 84.08, 1.0),
    ('ZC', 'Soy sauce', 'Dry- and other stock', 'ea', 'ea', 1, 98.28, 4.0),
    ('ZC', 'Strawberry jam', 'Dry- and other stock', 'ea', 'ea', 1, 65.09, 3.0),
    ('ZC', 'Sugar - Brown', 'Dry- and other stock', 'kg', 'kg', 1, 20.73, 5.0),
    ('ZC', 'Sugar - Castor', 'Dry- and other stock', 'kg', 'kg', 1, 23.4, 4.0),
    ('ZC', 'Sugar - Icing', 'Dry- and other stock', 'kg', 'kg', 1, 27.97, 6.0),
    ('ZC', 'Sugar- White', 'Dry- and other stock', 'kg', 'kg', 1, 18.78, 2.5),
    ('ZC', 'Sundried tomato', 'Dry- and other stock', 'ea', 'ea', 1, 35.99, 4.0),
    ('ZC', 'Sunflower seeds', 'Dry- and other stock', 'ea', 'ea', 1, 59.99, 3.0),
    ('ZC', 'Sweet Chili', 'Dry- and other stock', 'ea', 'ea', 1, 49.5, 0.0),
    ('ZC', 'Tabasco', 'Dry- and other stock', 'ml', 'ml', 1, 51.99, 0.0),
    ('ZC', 'Tennis biscuit', 'Dry- and other stock', 'ea', 'ea', 1, 23.99, 13.0),
    ('ZC', 'Terriyaki sauce', 'Dry- and other stock', 'ea', 'ea', 1, 83.99, 6.0),
    ('ZC', 'Tinned tomatoes', 'Dry- and other stock', 'ea', 'ea', 1, 14.03, 5.0),
    ('ZC', 'Tomato paste', 'Dry- and other stock', 'ea', 'ea', 1, 11.01, 15.0),
    ('ZC', 'Tomato sauce', 'Dry- and other stock', 'ml', 'ml', 1, 30.65, 3.0),
    ('ZC', 'Tortilla wraps', 'Dry- and other stock', 'ea', 'ea', 1, 37.99, 2.0),
    ('ZC', 'Tuna', 'Dry- and other stock', 'ea', 'ea', 1, 25.74, 5.0),
    ('ZC', 'Vanilla Essence', 'Dry- and other stock', 'L', 'L', 1, 51.67, 2.0),
    ('ZC', 'White vinegar', 'Dry- and other stock', 'L', 'L', 1, 10.05, 5.0),
    ('ZC', 'Whole grain mustard', 'Dry- and other stock', 'ea', 'ea', 1, 36.84, 0.0),
    ('ZC', 'Whole kennel corn', 'Dry- and other stock', 'ea', 'ea', 1, 24.99, 7.0),
    ('ZC', 'Wall nuts', 'Dry- and other stock', 'kg', 'kg', 1, 175.53, 4.0),
    ('ZC', 'Worchester sauce', 'Dry- and other stock', 'L', 'L', 1, 14.15, 2.0),
    ('ZC', 'Yeast', 'Dry- and other stock', 'ea', 'ea', 1, 213.69, 1.0),
    ('ZC', 'Caramel Treat', 'Dry- and other stock', 'ea', 'ea', 1, 30.55, 2.0),
    ('ZC', 'Polenta', 'Dry- and other stock', 'ea', 'ea', 1, 31.99, 2.0),
    ('ZC', 'Sweet Corn', 'Dry- and other stock', 'ea', 'ea', 1, 27.99, 12.0),
    ('ZC', 'Brown Rice', 'Dry- and other stock', 'kg', 'kg', 1, 25.99, 5.0),
    ('ZC', 'Golden syruo small', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 10.0),
    ('ZC', 'Golden syrup big', 'Dry- and other stock', 'ea', 'ea', 1, 63.99, 0.0),
    ('ZC', 'Maple Syrup smal', 'Dry- and other stock', 'ea', 'ea', 1, 39.99, 2.0),
    ('ZC', 'Maple syrup big', 'Dry- and other stock', 'ea', 'ea', 1, 63.99, 0.0),
    ('ZC', 'Honey small', 'Dry- and other stock', 'ea', 'ea', 1, 63.99, 4.0),
    ('ZC', 'Honey big', 'Dry- and other stock', 'ea', 'ea', 1, 99.0, 0.0),
    ('ZC', 'OrgininalChutney', 'Dry- and other stock', 'ea', 'ea', 1, 40.99, 10.0),
    ('ZC', 'Spaghetti', 'Dry- and other stock', 'ea', 'ea', 1, 19.99, 3.0),
    ('ZC', 'Chick peas', 'Dry- and other stock', 'ea', 'ea', 1, 26.99, 4.0),
    ('ZC', 'Red cherries', 'Dry- and other stock', 'ea', 'ea', 1, 98.99, 1.0),
    ('ZC', 'Green tabasco', 'Dry- and other stock', 'ea', 'ea', 1, 51.99, 6.0),
    ('ZC', 'Red tabasco', 'Dry- and other stock', 'ea', 'ea', 1, 109.99, 2.0),
    ('ZC', 'Cake flour', 'Dry- and other stock', 'kg', 'kg', 1, 17.99, 3.0),
    ('ZC', 'White wheat flour', 'Dry- and other stock', 'kg', 'kg', 1, 20.39, 0.0),
    ('ZC', 'Bread crumps', 'Dry- and other stock', 'ea', 'ea', 1, 29.99, 4.0),
    ('ZC', 'Mint sauce', 'Dry- and other stock', 'ea', 'ea', 1, 44.99, 2.0),
    ('ZC', 'Sweet & Sour', 'Dry- and other stock', 'ea', 'ea', 1, 77.99, 0.0),
    ('ZC', 'Pie Apple slices', 'Dry- and other stock', 'ea', 'ea', 1, 34.99, 2.0),
    ('ZC', 'Hot chocolate', 'Dry- and other stock', 'kg', 'kg', 1, 139.99, 1.0),
    ('ZC', 'Tickle Sugar', 'Dry- and other stock', 'kg', 'kg', 1, 0, 2.0),
    ('ZC', 'Cumin', 'Spices', 'ea', 'ea', 1, 42.99, 0.0),
    ('ZC', 'Curry', 'Spices', 'ea', 'ea', 1, 70.96, 1.0),
    ('ZC', 'Lemon and herb', 'Spices', 'ea', 'ea', 1, 60.36, 1.0),
    ('ZC', 'Aromat', 'Spices', 'ea', 'ea', 1, 131.42, 0.0),
    ('ZC', 'Mixed herbs', 'Spices', 'ea', 'ea', 1, 56.24, 1.0),
    ('ZC', 'Vegetable seasoning', 'Spices', 'ea', 'ea', 1, 138.5, 1.0),
    ('ZC', 'Vegetable stock', 'Spices', 'ea', 'ea', 1, 0, 1.0),
    ('ZC', 'Turmeric', 'Spices', 'ea', 'ea', 1, 154.97, 2.0),
    ('ZC', 'Salt', 'Spices', 'kg', 'kg', 1, 5.18, 5.0),
    ('ZC', 'Oregano', 'Spices', 'ea', 'ea', 1, 45.37, 2.0),
    ('ZC', 'Paprika spice', 'Spices', 'ea', 'ea', 1, 78.64, 1.0),
    ('ZC', 'Chicken spice', 'Spices', 'ea', 'ea', 1, 43.83, 1.0),
    ('ZC', 'Chicken stock', 'Spices', 'ea', 'ea', 1, 0, 1.0),
    ('ZC', 'Cajun spice', 'Spices', 'ea', 'ea', 1, 89.43, 1.0),
    ('ZC', 'Chip Seasoning', 'Spices', 'ea', 'ea', 1, 46.0, 1.0),
    ('ZC', 'Black pepper', 'Spices', 'ea', 'ea', 1, 410.17, 1.0),
    ('ZC', 'Rosemary', 'Spices', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Fish Spice', 'Spices', 'ea', 'ea', 1, 50.24, 1.0),
    ('ZC', 'Cinnamom ground', 'Spices', 'ea', 'ea', 1, 64.84, 2.0),
    ('ZC', 'Ground ginger', 'Spices', 'ea', 'ea', 1, 89.37, 1.0),
    ('ZC', 'Cayenne pepper', 'Spices', 'ea', 'ea', 1, 75.13, 1.0),
    ('ZC', 'Steak & Chop', 'Spices', 'ea', 'ea', 1, 57.79, 1.0),
    ('ZC', 'White Pepper', 'Spices', 'ea', 'ea', 1, 140.01, 0.0),
    ('ZC', 'Beef stock', 'Spices', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Nutmeg ground', 'Spices', 'ea', 'ea', 1, 255.78, 1.0),
    ('ZC', 'Meat tenderiser', 'Spices', 'ea', 'ea', 1, 58.35, 1.0),
    ('ZC', 'Thye', 'Spices', 'ea', 'ea', 1, 0, 0.0),
    ('ZC', 'Portugese chicken', 'Spices', 'ea', 'ea', 1, 53.28, 0.0),
    ('ZC', 'BBQ spice', 'Spices', 'ea', 'ea', 1, 62.8, 2.0),
    ('ZC', 'Mixed spice', 'Spices', 'ea', 'ea', 1, 87.64, 1.0),
    ('ZC', 'Pepper', 'Spices', 'ea', 'ea', 1, 0, 1.0),
    ('ZC', 'Course pepper', 'Spices', 'ea', 'ea', 1, 0, 0.0)
),
inserted as (
  insert into food_items (location_id, name, category, purchase_unit, recipe_unit, conversion_factor, min_units, max_units)
  select location_id, name, category, purchase_unit, recipe_unit, conversion_factor, 0, 0
  from new_items
  returning id, location_id, category, name
)
insert into food_stock_periods (item_id, location_id, period, opening_units, opening_cost_per_unit)
select inserted.id, inserted.location_id, '2026-07', new_items.stock, new_items.cost
from inserted
join new_items using (location_id, category, name)
on conflict (item_id, period) do update
  set opening_units = excluded.opening_units,
      opening_cost_per_unit = excluded.opening_cost_per_unit;
