// Crossing Lodges shared brand palette (same tokens as the ops app), pulled
// out of App.jsx so other components (e.g. BarcodeScanner.jsx) can use the
// same colors without a circular import back into App.jsx.

export const colors = {
  bg: "var(--surface)",
  panel: "var(--surface-raised)",
  border: "var(--line)",
  cream: "var(--text)",
  muted: "var(--text-muted)",
  navy: "var(--surface-overlay)",
  navyLt: "var(--line)",
  gold: "var(--accent)",
  goldLt: "var(--accent-hover)",
  ok: "var(--success)",
  danger: "var(--critical)",
  // Categorical chart colours. Series tokens rather than the accent, so a

  // lodge colour can never be mistaken for a status or for the brand.

  // Categorical chart colours. Series tokens rather than the accent, so a


  // lodge colour can never be mistaken for a status or for the brand.


  loc: { ZC: 'var(--series-1)', EC: 'var(--series-2)', SC: 'var(--series-3)' },
}

export const fonts = {
  body: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  heading: "'Cormorant Garamond', serif",
  mono: "'Space Mono', monospace",
}

// Left-sidebar shell CSS (2026-08-17) — ports the Ops/Maintenance app's
// `.shell`/`.sidebar`/`.nav` layout system into this app so the desktop menu
// bar matches theirs: logo + company/location switcher + tabs top-to-bottom
// on the left, footer with role badge/refresh/sign-out at the bottom.
// Class names deliberately match Ops's theme.js 1:1 (see that file) so any
// future layout tweak can be copied across every app without translation.
// Display toggling between the sidebar and the mobile bottom-sheet nav is
// done purely via these CSS classes (no inline `display` style on the
// elements themselves) — an inline style would always win over a
// non-`!important` media-query rule, which is exactly the trap the app's
// old `.desktop-tab-row`/`.mobile-nav-bar` inline-styled version fell into.
export const css = `
/* THEME-TOKENS-START — generated, do not hand-edit */
/* Generated by tools/rollout_theme.mjs from the Finance Dashboard's
   styles.css. Change it THERE and re-run; editing here means the seven apps
   drift apart one value at a time, invisibly. */
:root,
:root[data-theme='dark'] {
  color-scheme: dark;

  /* 1 — neutral base */
  --surface-sunken: #0f1216;
  --surface: #12161b;
  --surface-raised: #1a1f26;
  --surface-overlay: #222831;
  --line: #333c48;
  --text: #eef1f5;
  --text-muted: #9aa5b1;

  /* 2 — semantic, fixed */
  --success: #3dbe7a;
  --warning: #e8a33d;
  --critical: #f0736a;
  --informative: #63a8f0;

  /* 3 — accent. Overwritten at runtime by applyTheme(); this is only the
     fallback for a company with no accent set, and for the login screen
     which renders before any company is known. */
  --accent: #7c8cf8;
  --accent-hover: #93a0fa;
  --accent-active: #6675f0;
  --accent-contrast: #12161b;
  --accent-wash: rgba(124, 140, 248, 0.12);
  --accent-on-dark: #7c8cf8;
  --accent-on-dark-wash: rgba(124, 140, 248, 0.16);

  /* Elevation and shape. Previously both were hardcoded — one shadow value
     and 28 separate border-radius declarations — which meant "make the
     cards pop" was a find-and-replace rather than a setting. On a dark page
     lift comes from a darker shadow; on a light page it comes from a soft,
     slightly blue-tinted one. A neutral grey shadow on light looks dirty. */
  --radius-sm: 8px;
  --radius-md: 12px;
  --radius-lg: 16px;
  --shadow-sm: 0 1px 3px rgba(0, 0, 0, 0.35);
  --shadow-md: 0 4px 16px rgba(0, 0, 0, 0.4);
  --shadow-lg: 0 12px 32px rgba(0, 0, 0, 0.45);

  /* The sidebar rail is dark in BOTH modes — see SIDEBAR_SURFACE in
     theme.js. In dark mode it sits below the page; in light mode it becomes
     the navy chrome that makes the white cards read as floating. */
  /* Cards keep a hairline on dark (a shadow alone barely reads there) and
     drop it on light, where the shadow does the work and a border would
     make the card look pasted on. It's a token rather than a CSS override
     because four of the seven apps style their cards with INLINE style
     objects, which can't express "only in light mode". */
  --card-border: var(--line);

  --sidebar-bg: #0f1216;
  --sidebar-text: #e8edf4;
  --sidebar-muted: #8b97a6;
  --sidebar-line: rgba(255, 255, 255, 0.07);

  /* Categorical series for charts — distinguishable in order, and not
     reusing the semantic hues, so a chart series can never be mistaken for
     a status. */
  --series-1: #7c8cf8;
  --series-2: #4fc4cf;
  --series-3: #e8a33d;
  --series-4: #b98ee6;
  --series-5: #6ba5e7;
  --series-6: #d98a76;

  /* --- aliases: old names, new values -------------------------------- */
  --bg: var(--surface);
  --panel: var(--surface-raised);
  --panel-alt: var(--surface-overlay);
  --border: var(--line);
  --cream: var(--text);
  --muted: var(--text-muted);
  --navy: var(--surface-overlay);
  --navy-lt: var(--line);
  --gold: var(--accent);
  --gold-lt: var(--accent-hover);
  --ok: var(--success);
  --danger: var(--critical);
  --fuel-d: var(--informative);
  --fuel-p: var(--critical);
  --loc-zc: var(--series-1);
  --loc-ec: var(--series-2);
  --loc-sc: var(--series-3);

  --font-body: 'Inter', system-ui, -apple-system, sans-serif;
  --font-heading: 'Cormorant Garamond', Georgia, serif;
  --font-mono: 'Space Mono', ui-monospace, monospace;
}

/* Light is the shipped default for new companies: staff read this on phones
   outdoors, where a dark UI loses badly to direct sun, and the Reports pages
   print far better from light. Dark stays a per-user toggle. */
:root[data-theme='light'] {
  color-scheme: light;

  --surface-sunken: #eef1f5;
  --surface: #f7f9fb;
  --surface-raised: #ffffff;
  --surface-overlay: #f0f3f7;
  /* #d6dee7 was the obvious choice and measured 1.29:1 against --surface —
     a hairline that effectively vanishes, which matters most on the dense
     Budget vs Actual and Trial Balance tables, and worse on a phone in
     sunlight. #c3cfdc gives 1.50:1 and still reads as a light rule. */
  --line: #c3cfdc;
  --text: #161b22;
  --text-muted: #5a6572;

  /* Darker semantic variants — the dark-mode ones are far too light to pass
     contrast on a white panel. */
  --success: #0f7a45;
  --warning: #9a5b00;
  --critical: #b42318;
  --informative: #175cd3;

  --accent: #4338ca;
  --accent-hover: #3730a3;
  --accent-active: #312e81;
  --accent-contrast: #ffffff;
  --accent-wash: rgba(67, 56, 202, 0.09);
  /* The panel accent (#4338CA) would be almost invisible on the navy rail,
     so the rail gets a lightened variant of the same client colour. */
  --accent-on-dark: #a5b4fc;
  --accent-on-dark-wash: rgba(165, 180, 252, 0.16);

  /* Softer and blue-tinted rather than neutral grey: a grey shadow on a
     light surface reads as dirt, a slightly cool one reads as depth. */
  --shadow-sm: 0 1px 2px rgba(22, 32, 46, 0.06), 0 1px 3px rgba(22, 32, 46, 0.08);
  --shadow-md: 0 2px 4px rgba(22, 32, 46, 0.04), 0 6px 16px rgba(22, 32, 46, 0.09);
  --shadow-lg: 0 8px 28px rgba(22, 32, 46, 0.13);

  --card-border: transparent;
  --sidebar-bg: #16202e;

  --series-1: #4338ca;
  --series-2: #0e7490;
  --series-3: #9a5b00;
  --series-4: #7e22ce;
  --series-5: #1d4ed8;
  --series-6: #b04a2f;
}
/* THEME-TOKENS-END */





  body{background:${colors.bg};color:${colors.cream};font-family:'Inter',sans-serif}
  .shell{display:flex;min-height:100vh;background:${colors.bg};color:${colors.cream}}
  .sidebar{width:230px;background:${colors.panel};border-right:1px solid ${colors.border};display:flex;flex-direction:column;flex-shrink:0;position:sticky;top:0;height:100vh;overflow-y:auto}
  .main{flex:1;min-width:0;background:${colors.bg};color:${colors.cream}}
  .bottom-nav{display:none}

  .sidebar-logo{padding:20px 18px 16px;border-bottom:1px solid ${colors.border};display:flex;flex-direction:column;align-items:center;gap:8px}
  .sidebar-logo img{width:140px;height:auto;filter:brightness(0) invert(1) opacity(0.92)}
  .sidebar-sub{font-size:9px;letter-spacing:.2em;text-transform:uppercase;color:${colors.gold};font-weight:600;text-align:center;opacity:.85}
  .sidebar-company{font-size:11px;color:${colors.muted};text-align:center}

  .sidebar-select-wrap{padding:10px 13px;border-bottom:1px solid ${colors.border}}
  .sidebar-select{width:100%;background:rgba(0,0,0,.25);border:1px solid ${colors.border};border-radius:6px;padding:7px 9px;color:${colors.cream};font-family:'Inter',sans-serif;font-size:12px}
  .sidebar-select option{background:${colors.panel}}

  .loc-switcher{padding:12px 13px;border-bottom:1px solid ${colors.border};display:flex;flex-direction:column;gap:3px}
  .loc-label{font-size:9px;letter-spacing:.16em;text-transform:uppercase;color:${colors.muted};font-weight:600;margin-bottom:5px;padding-left:2px}
  .loc-btn{padding:7px 11px;border-radius:6px;border:1px solid transparent;font-family:'Inter',sans-serif;font-size:12px;font-weight:500;cursor:pointer;text-align:left;transition:all .15s;background:transparent;color:${colors.muted};display:flex;align-items:center;gap:8px;width:100%}
  .loc-btn:hover{color:${colors.cream};background:rgba(255,255,255,.04)}
  .loc-btn.active-ZC{background:rgba(184,147,90,.15);border-color:rgba(184,147,90,.45);color:${colors.gold}}
  .loc-btn.active-EC{background:rgba(91,140,196,.15);border-color:rgba(91,140,196,.45);color:${colors.loc.EC}}
  .loc-btn.active-SC{background:rgba(123,174,127,.15);border-color:rgba(123,174,127,.45);color:${colors.loc.SC}}
  .loc-dot{display:inline-block;width:7px;height:7px;border-radius:50%;flex-shrink:0}

  .period-wrap{padding:10px 13px;border-bottom:1px solid ${colors.border}}

  .nav{flex:1;padding:8px 0;overflow-y:auto}
  .nav-item{display:block;width:100%;text-align:left;padding:9px 18px;cursor:pointer;font-size:13px;font-weight:500;color:${colors.muted};transition:all .15s;border:none;background:none;border-right:2px solid transparent;letter-spacing:.01em}
  .nav-item:hover{color:${colors.cream};background:rgba(184,147,90,.06)}
  .nav-item.active{color:${colors.gold};background:rgba(184,147,90,.12);border-right-color:${colors.gold};font-weight:600}

  .sidebar-footer{padding:13px 18px;border-top:1px solid ${colors.border};font-size:10px;color:${colors.muted};line-height:1.6}
  .sidebar-footer-row{display:flex;gap:10px;margin-top:6px}
  .sidebar-footer-btn{background:none;border:none;color:${colors.muted};font-size:10px;cursor:pointer;padding:0;letter-spacing:.05em}

  /* Topbar — always visible (both desktop and mobile), same as Ops: page
     title + the account-level controls (company switcher, role badge,
     refresh, sign out) that live redundantly here as well as in the
     desktop sidebar, so they're still reachable once the sidebar hides on
     mobile. */
  .topbar{display:flex;flex-wrap:wrap;background:${colors.panel};border-bottom:1px solid ${colors.border};padding:14px 20px;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:10;gap:12px}
  .page-title{font-family:'Cormorant Garamond',serif;font-size:20px;font-weight:600;color:${colors.cream};letter-spacing:.02em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .topbar-select{background:rgba(0,0,0,.25);border:1px solid ${colors.border};border-radius:6px;padding:5px 8px;color:${colors.cream};font-family:'Inter',sans-serif;font-size:12px}
  .topbar-select option{background:${colors.panel}}
  .topbar-signout{background:none;border:1px solid ${colors.border};border-radius:6px;color:${colors.muted};font-size:11px;font-weight:600;cursor:pointer;padding:5px 10px;flex-shrink:0}

  /* Mobile-only location + period strip — sidebar already covers these on
     desktop, so this only needs to render <=768px. */
  .mobile-loc-bar{display:none}
  @media (max-width: 768px) {
    .mobile-loc-bar{
      display:flex;gap:6px;align-items:center;padding:8px 14px;
      background:${colors.panel};border-bottom:1px solid ${colors.border};
      overflow-x:auto;-webkit-overflow-scrolling:touch;
    }
    .mobile-loc-btn{
      flex-shrink:0;padding:5px 12px;border-radius:20px;border:1px solid transparent;
      font-family:'Inter',sans-serif;font-size:11px;font-weight:600;cursor:pointer;
      background:transparent;color:${colors.muted};display:flex;align-items:center;gap:5px;
      white-space:nowrap;
    }
    .mobile-loc-btn.active-ZC{background:rgba(184,147,90,.18);border-color:rgba(184,147,90,.5);color:${colors.gold}}
    .mobile-loc-btn.active-EC{background:rgba(91,140,196,.18);border-color:rgba(91,140,196,.5);color:${colors.loc.EC}}
    .mobile-loc-btn.active-SC{background:rgba(123,174,127,.18);border-color:rgba(123,174,127,.5);color:${colors.loc.SC}}
    .mobile-period-input{margin-left:auto;flex-shrink:0}
  }

  @media (max-width: 768px) {
    .sidebar{display:none}
    .bottom-nav{
      display:flex;position:fixed;bottom:0;left:0;right:0;
      background:${colors.panel};border-top:1px solid ${colors.border};
      z-index:10;padding:8px;padding-bottom:calc(8px + env(safe-area-inset-bottom));
      box-sizing:border-box;
    }
    .main{padding-bottom:70px}
  }


  /* ── Elevation + dark rail (2026-09-06) ────────────────────────────────
     Appended last so it wins over the earlier .sidebar rules without
     !important. The rail is dark in BOTH modes: against a light page that
     navy is what makes the cards read as floating, and it keeps the app's
     silhouette constant while a client accent changes only the highlights.
     Its text colours are fixed tokens, never --cream/--muted, because those
     flip with the mode and would turn near-black on navy in light mode. */
  .sidebar{background:var(--sidebar-bg);color:var(--sidebar-text);border-right:1px solid var(--sidebar-line)}
  .sidebar-logo{border-bottom-color:var(--sidebar-line)}
  .sidebar-sub{color:var(--accent-on-dark)}
  .sidebar-company{color:var(--sidebar-muted)}
  .sidebar-select-wrap{border-bottom-color:var(--sidebar-line)}
  .sidebar-select{border-color:var(--sidebar-line);color:var(--sidebar-text);border-radius:var(--radius-sm)}
  .sidebar-select option{background:var(--sidebar-bg);color:var(--sidebar-text)}
  .nav{padding:8px 10px}
  .nav-item{color:var(--sidebar-muted);border-right:none;border-radius:var(--radius-sm);padding:9px 12px}
  .nav-item:hover{color:var(--sidebar-text);background:rgba(255,255,255,.06)}
  .nav-item.active{color:var(--accent-on-dark);background:var(--accent-on-dark-wash);border-right:none}
  .sidebar-footer{border-top-color:var(--sidebar-line);color:var(--sidebar-muted)}
  .sidebar-footer-btn{color:var(--sidebar-muted)}
  .role-badge{border-color:var(--sidebar-line);color:var(--sidebar-muted)}
  .bottom-nav,.nav-sheet{background:var(--sidebar-bg);color:var(--sidebar-text)}
  .nav-sheet-item.active{color:var(--accent-on-dark);background:var(--accent-on-dark-wash)}
`
